name: Terraform

on:
  pull_request:
    paths: ['infra/**', '.github/workflows/terraform-deploy.yml']
  push:
    branches: [main]
    paths: ['infra/**', '.github/workflows/terraform-deploy.yml']
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: infra
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.14.6
      - uses: azure/login@v3
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - run: |
          terraform init \
          -backend-config="resource_group_name=${{ vars.AZURE_BACKEND_RG }}" \
          -backend-config="storage_account_name=${{ vars.AZURE_BACKEND_SA }}" \
          -backend-config="container_name=${{ vars.AZURE_BACKEND_CONTAINER }}" \
          -backend-config="key=${{ vars.AZURE_BACKEND_KEY }}"
      - run: terraform fmt -check
      - run: terraform validate

      - if: github.event_name == 'pull_request'
        id: plan
        run: terraform plan -no-color

      - if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        env:
          PLAN: ${{ steps.plan.outputs.stdout }}
        with:
          script: |
            const plan = process.env.PLAN || 'No output';
            const maxLen = 60000;
            const truncated = plan.length > maxLen
              ? plan.substring(0, maxLen) + '\n... (truncated)'
              : plan;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `#### Terraform Plan \n\`\`\`hcl\n${truncated}\n\`\`\``
            })

      - if: github.event_name != 'pull_request'
        run: terraform apply input=false -auto-approve
